---------------------------------------------------------
-- debug functions
---------------------------------------------------------

function onChat()
  local startTime = os.time()
  local obj = getObjectFromGUID("721ba2")
  local duration = os.time() - startTime
  log("GUID time: " .. duration)

  --
  local startTime = os.time()
  local obj = getObjectFromMemo({matColor = "Mythos", type = "PlayArea"})
  local duration = os.time() - startTime
  log("Memo time: " .. duration)

  --
  local startTime = os.time()
  local obj = getObjectFromMemo({matColor = "White", type = "InvestigatorSkillTracker"})
  local duration = os.time() - startTime
  log("Memo2 time: " .. duration)

  --
  local startTime = os.time()
  local obj = getObjectsWithTag("PlayArea")[1]
  local duration = os.time() - startTime
  log("Tag time: " .. duration)
end